name: CI

# Trigger on pull_request or on push to master
on:
  create:
    tags:
  push:
    branches:
      - master
  pull_request:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
        MY_VAR: Hi there! My name is
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: flake8
      run: |
        sudo apt-get install python3-pip
        pip3 install --user flake8==3.7.8
        ~/.local/bin/flake8
    - run: ./scripts/clang-format-diff.sh
    - run: ./scripte/clang-tidy-diff.sh

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: install ninja (linux)
      run: sudo apt-get install ninja-build
      if: matrix.os == 'ubuntu-latest'
    - name: install ninja (osx)
      run: brew install ninja
      if: matrix.os == 'macos-latest'
    - name: install ninja (win)
      run: choco install ninja
      if: matrix.os == 'windows-latest'
    - name: mkdir
      run: mkdir -p out
    - name: cmake (linux)
      run: cmake -S . -B out -G Ninja
      if: matrix.os == 'ubuntu-latest'
    - name: cmake (osx)
      run: cmake -S . -B out -G Ninja
      if: matrix.os == 'macos-latest'
    - name: cmake (win)
      # -G "Visual Studio 15 2017"
      run: cmake -S . -B out
      if: matrix.os == 'windows-latest'
    - name: build
      run: cmake --build out
    - name: test
      run: python check.py --binaryen-bin=out/bin
